platform :ios, '7.0'

pod 'Mantle', '1.5'
pod 'AFNetworking', '2.5.0'
pod 'CocoaLumberjack', '1.8.1'
pod 'SDWebImage', '~>3.7'
pod 'MBProgressHUD', '~> 0.9.2'
pod 'MJRefresh'
pod 'Masonry'
pod 'TTTAttributedLabel'
pod 'NJKWebViewProgress'
pod 'XZMRefresh'